server:
  port: 8100

spring:
  application:
    name: admin
  profiles:
    active: dev

eureka:
  client:
    service-url:
      # 浏览器访问不需要eureka，但配置必须要
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}

# Spring Boot Admin 本身也会注册到 Eureka，在监控列表中当然也包括对自身监控，可以暴露所有端点信息，不然在页面中无法查看监控数据：
management:
  endpoints:
    web:
      exposure:
        include: "*"
